import operationsData from'./operations.json'with{type:'json'};import provenance from'./provenance.json'with{type:'json'};import{Ajv,type ValidateFunction}from'ajv';import addFormats from'ajv-formats';import{open,lstat,unlink}from'node:fs/promises';import{constants}from'node:fs';import{isAbsolute}from'node:path';import{createHash}from'node:crypto';
import{DubClient,type Json,type QueryParam}from'../api/client.js';import{DubError,UsageError}from'../api/errors.js';import{selectAccount,type Config}from'../config.js';import type { Risk } from "@thenavidm/slipway";
export type Operation={name:string;operationId:string;title:string;description:string;method:string;path:string;group:string;risk:Risk;params:{name:string;key:string;in:string;required:boolean;schema:Json;style:string;explode:boolean}[];bodySchema:Json|null;bodyRequired:boolean;privateOutput:boolean};
export type ToolSpec={name:string;title:string;description:string;group:string;inputSchema:Json;risk:Risk;handler:(args:Json,client:DubClient)=>Promise<unknown>};
const operations=operationsData as unknown as Operation[];const ajv=new Ajv({allErrors:true,strict:false});(addFormats as unknown as(a:Ajv)=>void)(ajv);
// Each schema compiles on first use: compiling all of them at load held back the server's first answer. compileAll() runs them in tests.
const bodyValidators=new Map<string,ValidateFunction>();function bodyValidator(op:Operation):ValidateFunction{let v=bodyValidators.get(op.name);if(!v){v=ajv.compile(op.bodySchema!);bodyValidators.set(op.name,v);}return v;}
function check(v:ValidateFunction,a:unknown){if(!v(a))throw new UsageError(ajv.errorsText(v.errors,{separator:'; '}));}
function fieldsFor(op:Operation){const properties:Json=Object.fromEntries(op.params.map(p=>[p.key,p.schema]));Object.assign(properties,op.bodySchema?.properties??{});properties.account={type:'string',description:'Exact configured private workspace profile label; not a tenant or provider account ID.'};if(op.risk!=='read')properties.confirm={type:'boolean',description:'Must be true for the requested mutation or exclusive private output file.'};if(op.bodySchema){properties.payload={...op.bodySchema,description:'Complete native JSON body; do not mix with body flags or payload_file. Arrays use repeated JSON object flags or a whole native array in a private file.'};properties.payload_file={type:'string',minLength:1,description:'Absolute regular non-symlink JSON body file, at most 1 MiB. Cannot mix with payload/body flags.'};}if(op.privateOutput)properties.output_file={type:'string',minLength:1,description:'Required absolute new private file. Exclusive 0600 creation; never overwrites or echoes PNG/embed credentials.'};return{type:'object',properties,required:[...op.params.filter(p=>p.required).map(p=>p.key),...(op.privateOutput?['output_file']:[])],additionalProperties:false};}
async function fileJSON(path:string){let f;try{if(!isAbsolute(path)||(await lstat(path)).isSymbolicLink())throw Error();f=await open(path,constants.O_RDONLY|(constants.O_NOFOLLOW??0));const stat=await f.stat();if(!stat.isFile()||stat.size>1048576)throw Error();return JSON.parse(await f.readFile('utf8'));}catch{throw new UsageError('payload_file must be an absolute regular non-symlink JSON body file, at most 1 MiB.');}finally{await f?.close();}}
function semantics(op:Operation,args:Json,body:any){if(args.starting_after!==undefined&&args.ending_before!==undefined)throw new UsageError('starting_after and ending_before are mutually exclusive.');if(args.page!==undefined&&(args.starting_after!==undefined||args.ending_before!==undefined))throw new UsageError('Use a native cursor or deprecated page, without mixing them.');if(op.name==='get_link'&&!args.link_id&&!args.external_id&&!(args.domain&&args.key))throw new UsageError('get_link needs link_id, external_id, or both domain and key.');if(args.start&&args.end&&Date.parse(args.end)<=Date.parse(args.start))throw new UsageError('end must be after start.');if(args.start&&args.end&&args.interval)throw new UsageError('Use explicit start/end or interval, without mixing them.');if(op.method==='PATCH'&&body&&typeof body==='object'&&!Array.isArray(body)&&!Object.keys(body).length)throw new UsageError('Provide at least one field to update.');if(op.name==='bulk_create_links'&&(!Array.isArray(body)||body.length<1||body.length>100))throw new UsageError('Native link bulk creation requires 1–100 entries.');if(op.name==='bulk_update_links'&&(body.data.length<1||body.data.length>100))throw new UsageError('Native link bulk update requires 1–100 data entries.');if(op.name==='bulk_delete_links'&&(args.link_ids.length<1||args.link_ids.length>100))throw new UsageError('Native bulk delete requires 1–100 link IDs.');}
async function prepare(op:Operation,args:Json){const flat=Object.fromEntries(Object.keys(op.bodySchema?.properties??{}).filter(k=>args[k]!==undefined).map(k=>[k,args[k]]));if((args.payload!==undefined||args.payload_file!==undefined)&&Object.keys(flat).length)throw new UsageError('Do not mix body flags with payload/payload_file.');if(args.payload!==undefined&&args.payload_file!==undefined)throw new UsageError('Use payload or payload_file, not both.');let body=op.bodySchema?(args.payload_file?await fileJSON(args.payload_file):args.payload??flat):undefined;if(op.bodyRequired&&args.payload===undefined&&!args.payload_file&&!Object.keys(flat).length)throw new UsageError('This operation requires a native body; inspect schema and provide body flags, payload or payload_file.');if(op.bodySchema)check(bodyValidator(op),body);semantics(op,args,body);const path=op.params.filter(p=>p.in==='path').reduce((s,p)=>s.replace('{'+p.name+'}',encodeURIComponent(String(args[p.key]))),op.path);const query:QueryParam[]=op.params.filter(p=>p.in==='query'&&args[p.key]!==undefined).map(p=>({name:p.name,value:args[p.key],explode:p.explode}));return{method:op.method,path,query,body};}
async function execute(op:Operation,args:Json,client:DubClient){const call=await prepare(op,args);if(!op.privateOutput)return client.sanitize(await client.request(call.method,call.path,call.query,call.body,args.account));if(!isAbsolute(args.output_file))throw new UsageError('output_file must be absolute.');let handle;try{handle=await open(args.output_file,'wx',0o600);}catch{throw new UsageError('Cannot exclusively create output_file; use a new file in an existing private directory. Existing files are never overwritten.');}try{const data=await client.request(call.method,call.path,call.query,call.body,args.account);let bytes:Buffer;if(op.path==='/qr')bytes=data.binary_data;else{if(typeof data.publicToken!=='string'||!data.publicToken||typeof data.expires!=='string')throw new DubError('Embed-token response is incomplete; its outcome may be unknown. No automatic retry.');bytes=Buffer.from(JSON.stringify({publicToken:data.publicToken,expires:data.expires})+'\n');}await handle.writeFile(bytes);return{saved:true,output_file:args.output_file,bytes:bytes.length,content_type:op.path==='/qr'?'image/png':'application/json',sha256:createHash('sha256').update(bytes).digest('hex'),...(op.path==='/qr'?{}:{expires:data.expires}),notice:'Output is in the selected exclusive private file. Keep parent directory/Windows ACLs private; no automatic upload or browser preview.'};}catch(e){await handle.close();handle=undefined;await unlink(args.output_file).catch(()=>{});throw e;}finally{await handle?.close();}}
export const ALL_TOOLS:ToolSpec[]=operations.map(op=>({...op,inputSchema:fieldsFor(op),handler:(args,client)=>execute(op,args,client)}));
const account={type:'string',description:'Exact selected private workspace profile; binds label, not key ownership.'};const confirm={type:'boolean',description:'Explicit approval for this exact requested ordered batch.'};
function helper(name:string,title:string,description:string,risk:Risk,properties:Json,required:string[],handler:ToolSpec['handler']){ALL_TOOLS.push({name,title,description,group:'local_workflows',risk,inputSchema:{type:'object',properties,required,additionalProperties:false},handler});}
helper('list_accounts','List configured accounts','Local profile labels/default/auth method only. No keys, token paths, provider identity or network request.','read',{},[],async(_,c)=>({accounts:c.config.accounts.map(a=>({name:a.name,default:a.name===c.config.defaultAccount,auth:a.tokenFile?'token_file':a.apiToken?'api_key':'not_configured'}))}));
helper('get_operation_schema','Inspect a current native operation','Local reviewed method/path/query/body schema and provenance for one native tool. No credentials or provider request.','read',{operation:{type:'string',enum:operations.map(o=>o.name),description:'Exact native tool name, e.g. create_link or approve_program_application.'}},['operation'],async a=>({operation:operations.find(o=>o.name===a.operation),source:provenance.source,checked:provenance.checked,snapshotSha256:provenance.sanitizedSnapshotSha256}));
const allowed=operations.filter(o=>o.risk!=='read'&&['links','tags','folders'].includes(o.group)).map(o=>o.name);
const tasks={type:'array',minItems:1,maxItems:20,description:'One to twenty ordered link/tag/folder operations. CLI repeats --tasks with individual JSON objects; native bulk work still counts all affected records.',items:{type:'object',properties:{tool:{type:'string',enum:allowed},arguments:{type:'object',description:'Native tool arguments only; no account, confirm or payload_file. Use inline complete payload/native fields.'}},required:['tool','arguments'],additionalProperties:false}};
function canonical(v:any):any{if(Array.isArray(v))return v.map(canonical);if(v&&typeof v==='object')return Object.fromEntries(Object.keys(v).sort().map(k=>[k,canonical(v[k])]));return v;}
function hash(v:any){return createHash('sha256').update(JSON.stringify(canonical(v))).digest('hex');}
async function reviewed(args:Json,c:DubClient){const selected=selectAccount(c.config,args.account);const calls=[];for(const task of args.tasks){if(!allowed.includes(task.tool))throw new UsageError('Unsupported link batch tool.');if(['account','confirm','payload_file','output_file'].some(k=>task.arguments[k]!==undefined))throw new UsageError('Batch arguments cannot override account/confirmation or reference mutable payload files.');const t=ALL_TOOLS.find(t=>t.name===task.tool)!,op=operations.find(o=>o.name===task.tool)!;validateArguments(t,task.arguments);calls.push(await prepare(op,task.arguments));}return{version:1,profile:selected.name,snapshotSha256:provenance.sanitizedSnapshotSha256,tasks:args.tasks,calls};}
helper('preview_link_batch','Review exact ordered link tasks','Local validation and SHA-256 of exact ordered link/tag/folder work, selected profile label and reviewed schema. No provider reads, key load, identity check, price or rollback guarantee.','read',{tasks,account},['tasks'],async(a,c)=>{const r=await reviewed(a,c);return{...c.sanitize(r)as Json,reviewSha256:hash(r),localOnly:true,providerValidated:false,notice:'Binds profile label and exact requests/order/schema, not key ownership or changing provider state. Native bulk calls can affect up to 100 records each.'};});
helper('submit_link_batch','Execute reviewed link tasks','Confirmed one-to-twenty ordered link/tag/folder tasks. Prevalidate all and verify exact hash before first request. Stop on first failure with known results/failed index/unattempted indices; no retries, rollback or implicit continuation.','destructive',{tasks,account,confirm,review_sha256:{type:'string',pattern:'^[a-f0-9]{64}$',description:'Exact preview_link_batch hash for identical requests, profile label, schema and order.'}},['tasks','review_sha256'],async(a,c)=>{const r=await reviewed(a,c);if(hash(r)!==a.review_sha256)throw new UsageError('Review hash mismatch; preview these exact tasks and selected profile again.');const completed:Json[]=[];for(let i=0;i<r.calls.length;i++){const call=r.calls[i]!;try{const result=c.sanitize(await c.request(call.method,call.path,call.query,call.body,r.profile));completed.push({index:i,tool:a.tasks[i].tool,result});if(a.tasks[i].tool==='bulk_create_links'&&Array.isArray(result)&&result.some(item=>item&&typeof item==='object'&&typeof item.error==='string'))throw new DubError('Native bulk create returned per-link errors inside HTTP 200; earlier items may have succeeded. Inspect the included receipt before repeating.');}catch(e){const err=e as DubError;throw new DubError(JSON.stringify(c.sanitize({notice:'Batch stopped. Failed request may have an unknown outcome; inspect provider state before repeating. No retries or rollback.',completed,failedIndex:i,unattemptedIndices:r.calls.slice(i+1).map((_,j)=>i+1+j),error:err.message})),err.status??0,err.code??'API_ERROR');}}return{complete:true,completed};});
const validators=new Map<string,ValidateFunction>();function validatorFor(tool:ToolSpec):ValidateFunction{let v=validators.get(tool.name);if(!v){v=ajv.compile(tool.inputSchema);validators.set(tool.name,v);}return v;}export function validateArguments(tool:ToolSpec,args:Json){check(validatorFor(tool),args);}
/** Compile every input and body schema, as loading once did, so a test can prove they all compile. */
export function compileAll():number{for(const t of ALL_TOOLS)validatorFor(t);for(const o of operations)if(o.bodySchema)bodyValidator(o);return validators.size+bodyValidators.size;}export function visibleTools(c:Config){return ALL_TOOLS.filter(t=>!c.readOnly||t.risk==='read');}
